### ISSUE TITLE
EC2 : 배포 시스템은 생략하고 단순히 프로젝트를 EC2 서버에 띄우는 것을 먼저 진행.

### ISSUE THREAD

**Issue by devrokket** [Lucy-Arti/Arti-Server#5]
## 작업 내용
1. EC2 인스턴스 생성
2. 탄력적 IP + 인스턴스 연결
3. EC2 시작 
    - `chmod 400 arti-key.pem`
    - `ssh -i "arti-key.pem" ubuntu@ec2-{탄력적IP}.ap-northeast-2.compute.amazonaws.com`
5. EC2 환경에서 SSH 키 발급 받아서 github>setting에 new Key로 생성
    - <img width="795" alt="스크린샷 2023-09-11 오후 4 20 57" src="https://github.com/Lucy-Arti/Arti-Server/assets/96538554/3b1d442a-029b-497f-b090-e317508270f6">

6. `git clone {repo url}`
7. `sudo apt install openjdk-17-jdk`로 jdk 17 설치
8. `./gradlew build` 빌드
    - 로컬에서 `.gradlew build`를 실행하는 방식으로 진행: build/libs/내부에 .jar 파일이 생성됨을 확인하였다.
    - <img width="433" alt="스크린샷 2023-09-11 오후 4 28 09" src="https://github.com/Lucy-Arti/Arti-Server/assets/96538554/d9a994ee-aabc-46af-a4fd-e02093f75e97">
9. 내 도메인 한국에서 domain 받아서 탄력적 IP와 연결
http://arti.n-e.kr:8080/
10. 배포 완료
<img width="500" alt="스크린샷 2023-09-11 오후 8 07 39" src="https://github.com/Lucy-Arti/Arti-Server/assets/96538554/51d7d212-ebb1-41cb-b5ef-723c5e1bd811">

## 고민
- Spring Security가 만드는 로그인 화면을 없애기 위해서 `@SpringBootApplication(exclude = {SecurityAutoConfiguration.class})` 코드를 메인 함수 위에 작성함.
- 위 내용을 수정해도 로그인 페이지가 나오길래 왜 그럴지 고민하다가 build를 다시 안 해줘서 변경 사항이 저장 되어 있지 않다는 게 생각났습니다. 다음엔 까먹지 말기~!

## 질문사항
HTTPS로 미리 배포해두는 것이 좋을까요? 의견 부탁드립니다 !! @unanchoi 

## 참고 자료
https://velog.io/@jonghyun3668/SpringBoot-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-EC2-%EB%B0%B0%ED%8F%AC%ED%95%98%EA%B8%B0

**Comment by unanchoi** [comment]
우선 security 기본 로그인화면은 SecurityConfig class에서 제거할수있습니다~! 나중에 리팩토링 하면 좋을것같아요

HTTPS 배포는 클라이언트 배포상황에 맞춰서 적용해도될것같습니다!

추가로 ec에 nginx까지 적용 해주시면 좋을것같아요!

**Comment by devrokket** [comment]
```
@Override
protected void configure(HttpSecurity httpSecurity) throws Exception {
    httpSecurity.httpBasic().disable();
}

```
이렇게 SecurityConfig class에서 제거하는 방법이 있었네요..! 

ec2에 nginx 적용 해놓도록 하겠습니다 :)
